### ISSUE TITLE
Add option to include initial extensions values per request

### ISSUE THREAD

**Issue by kodieg** [TrueLayer/reqwest-middleware#1]
## Motivations

I would like to have a option to customize middleware behaviour per each request. For example, I could set per request retry policy, set some custom request identifier for logging, etc...

## Solution

I imagine this could be somehow solved by adding ability to set initial values for extensions.  Either by specifying initial Extensions value with new send_with_extensions method or maybe nicer by somehow wraping reqwest:: RequestBuilder to have context/data method (similar to actix_web::App.app_data)

**Comment by kodieg** [comment]
After reading a bit of crate code I think the best idea od to add to crate::RequestBuilder `pub fn data<T>(&mut self, data: T)` function that would insert `data` into extensions.

**Comment by TehPers** [comment]
Any news on this? I'd love to use this crate to add authentication and rate limiting middleware, but I can't pass request-specific data to the middleware yet.

I can work on this task and create a PR if that would help.

**Comment by LukeMathWalker** [comment]
@tl-rodrigo-gryzinski - can you have a look?

**Comment by tl-rodrigo-gryzinski** [comment]
@TehPers the PR would be welcome, go ahead :)
