### ISSUE TITLE
Parent span not set properly

### ISSUE THREAD

**Issue by julianocosta89** [TrueLayer/reqwest-middleware#120]
In the [OpenTelemetry Demo](https://github.com/open-telemetry/opentelemetry-demo) we have a Rust service using `reqwest-middleware`.
We have noticed that the Context Propagation is not working properly when using `reqwest` to call another service.
The issue is detailed in here: https://github.com/open-telemetry/opentelemetry-demo/issues/1318

But to add a full context to this issue, here is where we are using it:

```rust
async fn request_quote(count: u32) -> Result<f64, Box<dyn std::error::Error>> {
    // TODO: better testing here and default quote_service_addr
    let quote_service_addr: String = format!(
        "{}{}",
        env::var("QUOTE_SERVICE_ADDR").expect("$QUOTE_SERVICE_ADDR is not set"),
        "/getquote"
    );

    let mut reqbody = HashMap::new();
    reqbody.insert("numberOfItems", count);

    let client = ClientBuilder::new(reqwest::Client::new())
        .with(TracingMiddleware::<SpanBackendWithUrl>::new())
        .build();

    let req = client.request(Method::POST, quote_service_addr);

    let mut headers = HeaderMap::new();

    let cx = Context::current();
    global::get_text_map_propagator(|propagator| {
        propagator.inject_context(&cx, &mut HeaderInjector(&mut headers))
    });

    let resp = req
        .json(&reqbody)
        .headers(headers)
        .send()
        .await?
        .text_with_charset("utf-8")
        .await?;

    debug!("{:?}", resp);

    match resp.parse::<f64>() {
        Ok(f) => Ok(f),
        Err(error) => Err(Box::new(error)),
    }
}
```

When `shippingservice`(Rust) calls `quoteservice`(PHP) the `parent_id` sent is not from the caller, but from the caller's parent.
The trace is currenly looking like this:

![image](https://github.com/TrueLayer/reqwest-middleware/assets/15364991/56d86c18-7fac-45d3-bca7-232190f782f3)

But it should be something like this:

```
checkoutservice oteldemo.ShippingService/GetQuote
    |--> shippingservice oteldemo.ShippingService/GetQuote
        |--> shippingservice POST
            |--> quoteservice POST /getquote
                |--> quoteservice {closure}
                    |--> quoteservice calculate-quote
```

**Comment by julianocosta89** [comment]
Another thing that I wonder is why do we need to manually add the context to the headers?

I've removed the following and the trace context was totally gone from the headers.

```
let mut headers = HeaderMap::new();

    let cx = Context::current();
    global::get_text_map_propagator(|propagator| {
        propagator.inject_context(&cx, &mut HeaderInjector(&mut headers))
    });
```

Shouldn't the `reqwest` instrumentation handle that automatically?

**Comment by LukeMathWalker** [comment]
You're enabling `opentelemetry_0_20` (https://github.com/open-telemetry/opentelemetry-demo/blob/d8ecad7b975e662d0ab9096d7952f7e14497787c/src/shippingservice/Cargo.toml#L30) while using `opentelemetry = 0.21` in the same manifest (https://github.com/open-telemetry/opentelemetry-demo/blob/d8ecad7b975e662d0ab9096d7952f7e14497787c/src/shippingservice/Cargo.toml#L22).

If you switch to the correct feature everything should work as expected.
You shouldn't be setting the context yourself, the middleware does it for you (if configured correctly).

**Comment by julianocosta89** [comment]
Thank you @LukeMathWalker!

I've just submitted a PR fixing it: https://github.com/open-telemetry/opentelemetry-demo/pull/1433

Appreciate the help.
