### ISSUE TITLE
Support `reqwest@0.12` and `http@1`? 

### ISSUE THREAD

**Issue by dotansimha** [TrueLayer/reqwest-middleware#132]
related: https://github.com/TrueLayer/reqwest-middleware/pull/133
related: https://github.com/TrueLayer/reqwest-middleware/pull/127

**Comment by baraknaveh** [comment]
Isn't this now good to close? Or are we waiting for a release bump?

**Comment by eopb** [comment]
> Isn't this now good to close? Or are we waiting for a release bump?

This is good to close. The release will likely come next week. The reason for the delay is that I'm considering including https://github.com/TrueLayer/reqwest-middleware/pull/114 and https://github.com/TrueLayer/reqwest-middleware/pull/134 in the same breaking release.
