### ISSUE TITLE
Is there possibility to add proxy?

### ISSUE THREAD

**Issue by TheGP** [TrueLayer/reqwest-middleware#196]
If your stupid middleware returns own useless ClientBuilder, how I supposed to add proxy to the request?

**Comment by eopb** [comment]
Please word you issue more respectfully. Referring to this project as "stupid middleware" is unhelpful and not welcome here.

Consider this a [code of conduct](https://www.rust-lang.org/policies/code-of-conduct) warning. You're welcome to reopen your issue if you're able to word it constructively. You current issue is also underspecified so you will need to provide more details about what exactly you mean by proxy
