### ISSUE TITLE
[Question] Does this also retry on error of reading response?

### ISSUE THREAD

**Issue by Jared-Sprague** [TrueLayer/reqwest-middleware#47]
Hello!

I'm wondering if this would also try to retry if after a request is successful a failure occurs when reading the response?  

For example, if you are using a client built with retry would the retry policy also apply to errors getting the response: 

```
        let text = resp.text().await
```

**Comment by LukeMathWalker** [comment]
No, it does not - the middleware chain returns a `reqwest::Response` back, so it never attempts to read the body. That would happen in your application code.
