### ISSUE TITLE
Example given at https://crates.io/crates/reqwest-tracing does not work

### ISSUE THREAD

**Issue by bodemann** [TrueLayer/reqwest-middleware#5]
The example given at https://crates.io/crates/reqwest-tracing does not compile. There are spelling mistakes like `fun` instead of `fn` and some changes in the API were possibly not reflected.

I **suggest** the following fix: 

```
use opentelemetry::sdk::export::trace::stdout;
use reqwest_middleware::ClientBuilder;
use reqwest_tracing::TracingMiddleware;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::Registry;

#[tokio::main]
async fn main() {
    let tracer = stdout::new_pipeline().install_simple();
    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    let subscriber = Registry::default().with(telemetry);
    tracing::subscriber::set_global_default(subscriber).unwrap();

    run().await;
}

async fn run() {
    let client = ClientBuilder::new(reqwest::Client::new())
        .with(TracingMiddleware)
        .build();

    client.get("https://truelayer.com").send().await.unwrap();
}
```
I **suggest** to add the complete dependencies for the example since this would help beginners like me a lot. Here is what I used.
```
[dependencies]
tokio = { version = "1.10", features = ["full"] }
reqwest = "0.11.4"
opentelemetry = "0.16.0"
tracing-opentelemetry = "0.15.0"
reqwest-middleware = "0.1.0"
tracing-subscriber = "0.2.20"
reqwest-tracing = { version = "0.1.0", features = ["opentelemetry_0_16"] }
tracing = "0.1.26"
```

## To Reproduce
Try to compile the example with rust 1.54

## Expected behavior
A working example.

## Environment

- OS: [Linux (Manjaro)]
- Rust version: rustc 1.54.0 (a178d0322 2021-07-26)

## Additional context
**I am an beginner to Rust and tracing. So I might as well be wrong.**

**Comment by tl-rodrigo-gryzinski** [comment]
Thanks for the suggestion. We'll include the README in the doctests so this doesn't happen again
