### ISSUE TITLE
when is the next release happening?

### ISSUE THREAD

**Issue by rbtcollins** [TrueLayer/reqwest-middleware#69]
## Motivations

Would love to be able to use the new shiny without git references...

**Comment by rbtcollins** [comment]
@conradludgate ping ;)

**Comment by conradludgate** [comment]
Will be chatting with @tl-rodrigo-gryzinski today to try and get this out, thank you for your patience

**Comment by conradludgate** [comment]
reqwest-tracing 0.4.0
reqwest-middleware 0.2.0
reqwest-retry 0.2.0

all published
