### ISSUE TITLE
Implement Error.status()

### ISSUE THREAD

**Issue by jayvdb** [TrueLayer/reqwest-middleware#74]
## Motivations

The local `Error` is a simple enum between the underlying `reqwest::Error` and middleware errors.  It would be nice if this `Error` implemented the same interface as `reqwest::Error`, esp adding [`.status()`](https://github.com/seanmonstar/reqwest/blob/61474f4/src/error.rs#L148)

c.f. https://github.com/oxidecomputer/progenitor/pull/252 for why this could be useful.

**Comment by conradludgate** [comment]
Great idea, thanks for the suggestion. I have no opposition to this
