### ISSUE TITLE
Support opentelemetry 0.19

### ISSUE THREAD

**Issue by jayvdb** [TrueLayer/reqwest-middleware#85]
## Motivations

0.19 has been released

https://docs.rs/opentelemetry/0.19.0/opentelemetry/

**Comment by jayvdb** [comment]
tracing-opentelemetry has not yet been updated to support opentelemetry 0.19

blocked on https://github.com/tokio-rs/tracing-opentelemetry/pull/12

**Comment by kingli-crypto** [comment]
Seems https://github.com/tokio-rs/tracing-opentelemetry/pull/12 has merged
