### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jayvdb** [TrueLayer/reqwest-middleware#95]
With https://github.com/TrueLayer/reqwest-middleware/issues/85 now fixed, it would be nice to have a release so that users can upgrade their Otel stack.

What open issues need to be addressed before a release can be cut?

**Comment by tl-rodrigo-gryzinski** [comment]
Hey @jayvdb! `reqwest-tracing` v0.4.5 was released yesterday with support for opentelemetry 0.19.
